from modelscope import snapshot_download
model_dir = snapshot_download('ZhipuAI/cogvlm2-llama3-chat-19B')
model_dir = snapshot_download('ZhipuAI/cogvlm2-video-llama3-chat')
#model_dir = snapshot_download('maple77/Mini-InternVL-Chat-2B-V1-5')
#model_dir = snapshot_download('maple77/Mini-InternVL-Chat-4B-V1-5')
#model_dir = snapshot_download('qwen/Qwen2-7B-Instruct')
#model_dir = snapshot_download('qwen/Qwen2-72B-Instruct')
#model_dir = snapshot_download('deepseek-ai/DeepSeek-V2-Chat')
#model_dir = snapshot_download('deepseek-ai/DeepSeek-V2-Lite-Chat')
#model_dir = snapshot_download('LLM-Research/Meta-Llama-3-8B-Instruct')
#model_dir = snapshot_download('AI-ModelScope/Mixtral-8x7B-Instruct-v0.1')
#model_dir = snapshot_download('LLM-Research/Meta-Llama-3-8B')
#model_dir = snapshot_download('Shanghai_AI_Laboratory/internlm2-chat-7b')
#model_dir = snapshot_download('AI-ModelScope/InternVL-Chat-V1-5')
